name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *
    - cron: 00 06 * * 1-5

jobs:
  run-postman-test:
    runs-on: ubuntu-latest


    steps:
      - name: checkout the code
        uses: actions/checkout@v4.3.1

      - name: InstallNodeJs and npm
        uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'

      - name: Install newman globally
        run: |
             npm install -g newman 
             npm install -g newman-reporter-htmlextra

      - name: Run the collection using newman
        run: |
             newman run 'InWarranty-Flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -r cli,htmlextra
             
             
        

        
      
      
      
    
    
